### ISSUE TITLE
transform操作能保证对原图和分割图做的操作是一样的吗？

### ISSUE THREAD

**Issue by xyf9474** [lee-zq/3DUNet-Pytorch#25]
dataset文件夹下的dataset_lists_train文件中对数据的transform操作怎么能保证对原图和分割图做的操作是一样的呢？
感觉这样transform是不对的，我改成别的方法了

**Comment by jielingao** [comment]
看下代码啊，都是同步操作啊

**Comment by xyf9474** [comment]
谢谢，已经看过解决了，有问题再请教你




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月18日(星期二) 下午4:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lee-zq/3DUNet-Pytorch] transform操作能保证对原图和分割图做的操作是一样的吗？ (Issue #25)





 
看下代码啊，都是同步操作啊
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
